"""Enforce UserRole enum

Revision ID: aa94da20f869
Revises: 725a06571f8e
Create Date: 2026-06-13 13:28:57.205115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa94da20f869'
down_revision: Union[str, Sequence[str], None] = '725a06571f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = sa.Enum('agent', 'customer', 'admin', name='userrole')
    userrole_enum.create(op.get_bind())
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('agent', 'customer', 'admin', name='userrole'),
               existing_nullable=False,
               postgresql_using='role::userrole')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('agent', 'customer', 'admin', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    userrole_enum = sa.Enum('agent', 'customer', 'admin', name='userrole')
    userrole_enum.drop(op.get_bind())
    # ### end Alembic commands ###
